spring.application.name=webmars-api
spring.datasource.url=jdbc:postgresql://localhost:5432/webmars
spring.datasource.username=postgres
spring.datasource.password=JHP715BaLL$M@ui
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true